FROM ubuntu:latest

ENV GCC_VERSION=11
ENV CLANG_VERSION=12
ENV DEBIAN_FRONTEND=noninteractive

ENV TBB_VERSION=2021.5.0
ENV TBB_INSTALL_DIR=/usr/local
ENV TBB_DIR=${TBB_INSTALL_DIR}/oneapi-tbb-${TBB_VERSION}/lib/cmake/tbb

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y -qq software-properties-common lsb-release wget git
RUN add-apt-repository -y ppa:ubuntu-toolchain-r/test

RUN apt-get install -y -qq gcc-${GCC_VERSION} gcc-${GCC_VERSION}-multilib
RUN apt-get install -y -qq g++-${GCC_VERSION} g++-${GCC_VERSION}-multilib
RUN apt-get install -y -qq clang-${CLANG_VERSION}

RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
RUN apt-add-repository -y "deb https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main"
RUN apt-get install -y -qq kitware-archive-keyring
RUN rm /etc/apt/trusted.gpg.d/kitware.gpg
RUN apt-get install -y -qq cmake

RUN apt-get install -y -qq python3-dev python-is-python3 python3.8-venv python3-pip
RUN apt-get install -y -qq libopencv-dev

WORKDIR ${TBB_INSTALL_DIR}
RUN wget https://github.com/oneapi-src/oneTBB/releases/download/v${TBB_VERSION}/oneapi-tbb-${TBB_VERSION}-lin.tgz
RUN tar zxvf oneapi-tbb-${TBB_VERSION}-lin.tgz
