name: Publish docker images

on:
  push:
    branches: [ latest ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ latest ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  UBUNTU_OPENCV: ubuntu-opencv

jobs:
  push_to_registries:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
     
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
           ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.UBUNTU_OPENCV }}
           ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.UBUNTU_OPENCV }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile-${{ env.UBUNTU_OPENCV }}
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.UBUNTU_OPENCV }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.UBUNTU_OPENCV }}:buildcache,mode=max
